# Generated by Django 5.2.3 on 2025-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='jti',
            field=models.CharField(default='jti', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='replaced_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
