# Generated by Django 5.2.3 on 2025-09-05 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], db_index=True, default='Easy', max_length=10)),
                ('examples', models.JSONField(default=list)),
                ('constraints', models.TextField()),
                ('hints', models.JSONField(blank=True, default=list, null=True)),
                ('editorial', models.TextField()),
                ('testcases', models.JSONField(blank=True, default=list, null=True)),
                ('code_snippets', models.JSONField(blank=True, default=list, null=True)),
                ('reference_solutions', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(db_index=True, related_name='problems', to='core.tag')),
            ],
        ),
    ]
