# Generated by Django 5.2.3 on 2025-09-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='editorial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='examples',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='reference_solutions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='testcases',
            field=models.JSONField(default=list),
        ),
    ]
