# Generated by Django 5.2.3 on 2025-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submission_submissiontestcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontestcase',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
